% Function that displays aircraft sizing results

function [] = ReportFunction(inputs)
fprintf('%s \n','------------------------------------          ')
fprintf('Maximum Payload\n')
fprintf('%s%7.0f%s \n','Takeoff Gross Weight:  ',inputs.DesignTOGW,' lbs')
fprintf('%s%7.0f%s \n','Fuel Weight:           ',inputs.DesignWfuel,' lbs')
fprintf('%s%7.0f%s \n','Payload Weight:        ',inputs.DesignInputs.w_payload,' lbs')
fprintf('%s%7.0f%s \n','Empty Weight:          ',inputs.EmptyWeight.We,' lbs')
fprintf('%s%7.3f%s \n','We/W0:                 ',inputs.EmptyWeight.We/inputs.DesignTOGW,'')
fprintf('%s \n','------------------------------------          ')

fprintf('%s \n','------------------------------------          ')
fprintf('Medium Payload\n')
fprintf('%s%7.0f%s \n','Takeoff Gross Weight:  ',inputs.MediumTOGW,' lbs')
fprintf('%s%7.0f%s \n','Fuel Weight:           ',inputs.MediumWfuel,' lbs')
fprintf('%s%7.0f%s \n','Payload Weight:        ',inputs.MediumInputs.w_payload,' lbs')
fprintf('%s%7.0f%s \n','Empty Weight:          ',inputs.EmptyWeight.We,' lbs')
fprintf('%s%7.3f%s \n','We/W0:                 ',inputs.EmptyWeight.We/inputs.MediumTOGW,'')
fprintf('%s \n','------------------------------------          ')

fprintf('%s \n','------------------------------------          ')
fprintf('Ferry\n')
fprintf('%s%7.0f%s \n','Takeoff Gross Weight:  ',inputs.FerryTOGW,' lbs')
fprintf('%s%7.0f%s \n','Fuel Weight:           ',inputs.FerryWfuel,' lbs')
fprintf('%s%7.0f%s \n','Payload Weight:        ',inputs.FerryInputs.w_payload,' lbs')
fprintf('%s%7.0f%s \n','Empty Weight:          ',inputs.EmptyWeight.We,' lbs')
fprintf('%s%7.3f%s \n','We/W0:                 ',inputs.EmptyWeight.We/inputs.FerryTOGW,'')
fprintf('%s \n','------------------------------------          ')

fprintf('%s \n','------------------------------------          ')
fprintf('Wing Parameters\n')
fprintf('%s%7.3f%s \n','Aspect Ratio:          ',inputs.GeometryOutput.AR,'')
fprintf('%s%7.0f%s \n','Wing Loading:          ',inputs.PerformanceInputs.WS,' lbs/ft^2')
fprintf('%s%7.0f%s \n','Wing Area:             ',inputs.GeometryOutput.Sw,' ft^2')
fprintf('%s%7.0f%s \n','Wing Span:             ',inputs.GeometryInputs.b,' ft')
fprintf('%s \n','------------------------------------          ')
% inputs.GeometryInputs.AR*inputs.PerformanceInputs.WS/inputs.TOGW
% fprintf('%s \n','Empty Weight breakdown          ')
% fprintf('%s \n','____________________________________          ')
% fprintf('%s%6.0f%s \n','           Wing:        ',inputs.EmptyWeight.Wwing,' lbs')
% fprintf('%s%6.0f%s \n','           Fuselage:    ',inputs.EmptyWeight.Wfus,' lbs')
% fprintf('%s%6.0f%s \n','           Vtail:       ',inputs.EmptyWeight.WVtail,' lbs')
% fprintf('%s%6.0f%s \n','           Htail:       ',inputs.EmptyWeight.WHtail,' lbs')
% fprintf('%s%6.0f%s \n','           Engines:     ',inputs.EmptyWeight.Weng,' lbs')
% fprintf('%s%6.0f%s \n','           Gear:        ',inputs.EmptyWeight.Wgear,' lbs')
% fprintf('%s%6.0f%s \n','           Misc:        ',inputs.EmptyWeight.Wmisc,' lbs')
% fprintf('%s \n','------------------------------------          ')
% fprintf('%s \n','Costs          ')
% fprintf('%s \n','____________________________________          ')
% fprintf('%s%6.0f%s \n','Acquisition Cost:       $ ',inputs.AqCostOutput.AqCost,' ')
% fprintf('%s%6.0f%s \n','Operating Cost (DOC+I): $   ',inputs.OpCostOutput.DOC_leg,' /leg')
% fprintf('%s%6.0f%s \n','Operating Cost (DOC+I): $   ',inputs.OpCostOutput.DOC_BH,' /BH')
