% Function that displays aircraft sizing results

function [] = ReportFunction(inputs)
fprintf('%s \n','------------------------------------          ')
fprintf('Maximum Payload\n')
fprintf('%s%6.0f%s \n','Takeoff Gross Weight:  ',inputs.TOGW,' lbs')
fprintf('%s%6.0f%s \n','Fuel Weight:           ',inputs.WfuelMaxPL,' lbs')
fprintf('%s%6.0f%s \n','Payload Weight:        ',inputs.DesignInputs.w_payload,' lbs')
fprintf('%s%6.0f%s \n','Empty Weight:          ',inputs.EmptyWeight.We,' lbs')
fprintf('%s%6.3f%s \n','We/W0:                 ',inputs.EmptyWeight.We/inputs.TOGW,'')
fprintf('%s \n','------------------------------------          ')

fprintf('%s \n','------------------------------------          ')
fprintf('Medium Payload\n')
fprintf('%s%6.0f%s \n','Takeoff Gross Weight:  ',inputs.WtoMedPL,' lbs')
fprintf('%s%6.0f%s \n','Fuel Weight:           ',inputs.WfuelMedPL,' lbs')
fprintf('%s%6.0f%s \n','Payload Weight:        ',inputs.MediumInputs.w_payload,' lbs')
fprintf('%s%6.0f%s \n','Empty Weight:          ',inputs.EmptyWeight.We,' lbs')
fprintf('%s%6.3f%s \n','We/W0:                 ',inputs.EmptyWeight.We/inputs.WtoMedPL,'')
fprintf('%s \n','------------------------------------          ')

fprintf('%s \n','------------------------------------          ')
fprintf('Ferry\n')
fprintf('%s%6.0f%s \n','Takeoff Gross Weight:  ',inputs.WtoFerry,' lbs')
fprintf('%s%6.0f%s \n','Fuel Weight:           ',inputs.WfuelFerry,' lbs')
fprintf('%s%6.0f%s \n','Payload Weight:        ',inputs.FerryInputs.w_payload,' lbs')
fprintf('%s%6.0f%s \n','Empty Weight:          ',inputs.EmptyWeight.We,' lbs')
fprintf('%s%6.3f%s \n','We/W0:                 ',inputs.EmptyWeight.We/inputs.WtoMedPL,'')
fprintf('%s \n','------------------------------------          ')

% fprintf('%s \n','Empty Weight breakdown          ')
% fprintf('%s \n','____________________________________          ')
% fprintf('%s%6.0f%s \n','           Wing:        ',inputs.EmptyWeight.Wwing,' lbs')
% fprintf('%s%6.0f%s \n','           Fuselage:    ',inputs.EmptyWeight.Wfus,' lbs')
% fprintf('%s%6.0f%s \n','           Vtail:       ',inputs.EmptyWeight.WVtail,' lbs')
% fprintf('%s%6.0f%s \n','           Htail:       ',inputs.EmptyWeight.WHtail,' lbs')
% fprintf('%s%6.0f%s \n','           Engines:     ',inputs.EmptyWeight.Weng,' lbs')
% fprintf('%s%6.0f%s \n','           Gear:        ',inputs.EmptyWeight.Wgear,' lbs')
% fprintf('%s%6.0f%s \n','           Misc:        ',inputs.EmptyWeight.Wmisc,' lbs')
% fprintf('%s \n','------------------------------------          ')
% fprintf('%s \n','Costs          ')
% fprintf('%s \n','____________________________________          ')
% fprintf('%s%6.0f%s \n','Acquisition Cost:       $ ',inputs.AqCostOutput.AqCost,' ')
% fprintf('%s%6.0f%s \n','Operating Cost (DOC+I): $   ',inputs.OpCostOutput.DOC_leg,' /leg')
% fprintf('%s%6.0f%s \n','Operating Cost (DOC+I): $   ',inputs.OpCostOutput.DOC_BH,' /BH')
